repurposed the scripts

diff --git a/archinstall b/archinstall
--- a/archinstall
+++ b/archinstall
@@ -16,26 +16,16 @@ welcome() {
 This script installs a minimal Arch Linux system."
 }
 
-get_username() {
-  username=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Account name: " \
-    --placeholder "(enter a name for the user account)")
-  while ! echo "$username" | grep -q "^[a-z_][a-z0-9_-]*$"; do
-    username=$(gum input --prompt.foreground 99 --prompt.bold \
-      --prompt "Try again. Account name: " \
-      --placeholder "(only lowercase letters, - and _ are allowed)")
-  done
-}
-
 get_password() {
   password=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Password: " \
-    --password --placeholder "(enter a password for $username)")
+    --password --placeholder "(enter a password for root")
   verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
     --password --placeholder "(retype the password)")
   while [ -z "$password" ] || [ "$password" != "$verify" ]; do
     unset verify
     password=$(gum input --prompt.foreground 99 --prompt.bold \
       --prompt "Try again. Password: " --password \
-      --placeholder "(enter a password for $username)")
+      --placeholder "(enter a password for root)")
     verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
       --password --placeholder "(retype the password)")
   done
@@ -56,7 +46,8 @@ set_keymap() {
   while [ -z "$keymap" ]; do
     # choose a keymap
     keymap=$(localectl list-keymaps --no-pager | gum filter --prompt.foreground 93 \
-      --prompt.bold --prompt "Keymap: " --placeholder "(search for your keyboard layout)")
+      --prompt.bold --prompt "Keymap: " --value "us" \
+      --placeholder "(search for your keyboard layout)")
   done
   # load the selected keymap
   loadkeys "$keymap"
@@ -67,7 +58,8 @@ get_timezone() {
   while [ -z "$timezone" ]; do
     # choose a timezone
     timezone=$(timedatectl list-timezones --no-pager | gum filter --prompt.foreground 93 \
-      --prompt.bold --prompt "Timezone: " --placeholder "(search for your timezone)")
+      --prompt.bold --prompt "Timezone: " --value "New_York" \
+      --placeholder "(search for your timezone)")
   done
   # synchronize the network time protocol
   timedatectl set-ntp true
@@ -83,8 +75,8 @@ disk_partition() {
       --prompt.foreground 93 --prompt.bold --prompt "Disk name: " \
       --placeholder "(select the disk to partition)" | cut -d' ' -f1)
   done
-  # nvme drives uses the 'p' label for the partition
-  label=$(echo "$diskname" | grep -q "nvme" && printf '%s' "p")
+  # nvme drives use 'p' to label partitions
+  nvme_label=$(echo "$diskname" | grep -q "nvme" && printf '%s' "p")
   # show the recommended layout and prompt the user
   gum confirm --prompt.foreground 99 --prompt.border-foreground 105 \
     --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border thick \
@@ -92,8 +84,8 @@ disk_partition() {
     --default "$(gum format -t markdown "# Recommended Partition Layout
 Mountpoint|Partition|ID Type|Suggested Size
 -|-|-|-
-/mnt/boot|${diskname}${label}1|ef EFI|512 MiB
-/mnt|${diskname}${label}2|83 Linux|Remaining size")
+/mnt/boot|${diskname}${nvme_label}1|ef EFI|512 MiB
+/mnt|${diskname}${nvme_label}2|83 Linux|Remaining size")
 
 Only an EFI and root partition are required.
 You may also opt to partition the disk in any other way.
@@ -159,7 +151,7 @@ input_confirmation() {
     --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border rounded \
     --default "$(gum format -t markdown "username|password|hostname|keymap|timezone
 -|-|-|-|-
-${username}|${hidden}|${hostname}|${keymap}|${timezone}
+root|${hidden}|${hostname}|${keymap}|${timezone}
 
 disk|efi part|format|root part|swap
 -|-|-|-|-
@@ -207,8 +199,6 @@ pacman --noconfirm --needed -Sy gum >/dev/null 2>&1 ||
 
 welcome || end "bye bye"
 
-get_username
-
 get_password
 
 get_hostname
@@ -228,10 +218,7 @@ get_root_partition || end "something went wrong at get_root_partition"
 suggest_swapfile || end "something went wrong at suggest_swapfile"
 
 while input_confirmation; do
-  case "$(gum choose "username" "password" "host" \
-    "keymap" "timezone" "disk" "efi" "root" "swap")" in
-    username)
-      get_username ;;
+  case "$(gum choose "password" "host" "keymap" "timezone" "disk" "efi" "root" "swap")" in
     password)
       get_password ;;
     host)
@@ -258,7 +245,7 @@ final_prompt || end "exited"
 # header
 gum style --bold --foreground 99 "Updating archlinux-keyring"
 
-# refresh archlinux keyring and install reflector if missing
+# refresh archlinux keyring and install some additional packages
 pacman --needed --noconfirm -S archlinux-keyring reflector curl ca-certificates ||
   end "pacman failed, please make sure you have an internet connection"
 
@@ -292,11 +279,11 @@ gum style --bold --foreground 99 "Installing core packages"
 
 # install the core packages in a single pacstrap call (required to generate initramfs)
 gum spin --spinner line --title "Installing core packages..." -- pacstrap -K /mnt \
-  linux linux-firmware linux-headers base base-devel ${vendor}-ucode grub efibootmgr zsh \
-  dash git gum reflector networkmanager neovim terminus-font curl ca-certificates ||
+  linux linux-firmware linux-headers base base-devel ${vendor}-ucode grub efibootmgr \
+  dash doas git gum reflector networkmanager neovim terminus-font curl ca-certificates ||
     end "core packages failed, please make sure you have an internet connection"
 
-echo "installed all the core packages."
+echo "installed all the core packages"
 
 # needed to connect to the internet on reboot
 arch-chroot /mnt systemctl enable NetworkManager
@@ -364,8 +351,9 @@ EOT
 # header
 gum style --bold --foreground 99 "Creating users"
 
-arch-chroot /mnt useradd -m -s /usr/bin/zsh "$username" &&
-  printf '%b\n' "created user \033[32m${username}\033[0m"
+pacstrap -K /mnt zsh > /dev/null 2>&1 &&
+  arch-chroot /mnt useradd -m -s /usr/bin/zsh "$username" &&
+    printf '%b\n' "created user \033[32m${username}\033[0m"
 
 # set password for the new user
 echo "$username:$password" | arch-chroot /mnt chpasswd ||
@@ -386,26 +374,78 @@ sed -i '/^#Color/s/^#//;/^#ILoveCandy/s/^#//;/^#ParallelDownloads/s/^#//' /mnt/e
 # use all cores when compiling packages with makepkg
 sed -i "/^#MAKEFLAGS/s/^#//;s/-j2/-j$(nproc)/" /mnt/etc/makepkg.conf
 
+### PACMAN HOOKS ###
+
+# header
+gum style --bold --foreground 99 "Creating pacman hooks"
+
+# create the hooks directory if it does not exist
+[ ! -d /mnt/etc/pacman.d/hooks ] && mkdir -p /mnt/etc/pacman.d/hooks
+
+# hook to check for orphans after installing, upgrading, or removing a package
+tee /mnt/etc/pacman.d/hooks/orphans.hook >/dev/null << EOF
+[Trigger]
+Operation = Remove
+Type = Package
+Target = *
+
+[Action]
+Description = Searching for orphaned packages...
+When = PostTransaction
+Exec = /usr/bin/sh -c '/usr/bin/pacman -Qtdq || /usr/bin/printf ""'
+EOF
+
+# hook to remove zsh newuser script if it exists
+tee /mnt/etc/pacman.d/hooks/zsh-newuser.hook >/dev/null << EOF
+[Trigger]
+Operation = Install
+Operation = Upgrade
+Type = Package
+Target = zsh
+
+[Action]
+Description = Removing zsh newuser script...
+When = PostTransaction
+Exec = /usr/bin/rm -f /usr/share/zsh/scripts/newuser
+EOF
+
+# map the <ESC> to the physical Caps Lock key and disable the Esc key
+tee /mnt/etc/pacman.d/hooks/esc2caps.hook >/dev/null << EOF
+[Trigger]
+Operation = Install
+Operation = Upgrade
+Type = File
+Target = /usr/share/X11/xkb/keycodes/evdev
+
+[Action]
+Description = Unsetting Esc and mapping its function to the Caps Lock key...
+When = PostTransaction
+Exec = /usr/share/libalpm/scripts/esc2caps
+EOF
+
+# script to do the key mapping
+tee /mnt/usr/share/libalpm/scripts/esc2caps >/dev/null << EOT
+#!/bin/sh
+
+evdev='/usr/share/X11/xkb/keycodes/evdev'
+mapped=\$(/usr/bin/grep -o '<ESC> = 66;' \$evdev)
+
+if  [ -z "\$mapped" ]; then
+  sed -i 's/<CAPS> = 66/\/\/ <CAPS> = 66/' \$evdev # unset the <CAPS> keymap
+  sed -i 's/<ESC> = 9/<ESC> = 66/' \$evdev # map <ESC> to Caps Lock (keycode 66)
+  sed -i 's/<HENK> = 100/<HENK> = 9/' \$evdev # map <HENK> the Esc (keycode 9)
+fi
+
+unset evdev mapped
+EOT
+
+# change permission to -rwxr-xr-x
+chmod 755 /mnt/usr/share/libalpm/scripts/esc2caps || echo "[script] permission failed"
+
 ### USER CONFIGURATION ###
-
-# permit user to sudo with password
-echo "%${username} ALL=(ALL:ALL) ALL" > /mnt/etc/sudoers.d/00-"${username}"
-
-# allow some system commands to run without password
-echo "%${username} ALL=(ALL:ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/mount,\
-  /usr/bin/umount,/usr/bin/pacman --noconfirm -S,/usr/bin/pacman -S,/usr/bin/pacman -Sy,\
-  /usr/bin/pacman -Syu" > /mnt/etc/sudoers.d/01-no-password-commands
-
-# set the default editor for visudo
-echo "Defaults editor=/usr/bin/nvim" > /mnt/etc/sudoers.d/02-visudo-editor
-
-# permit the wheel group to use doas with password
-echo "permit persist keepenv :${username}" > /mnt/etc/doas.conf
 
 # beep begone!
 rmmod pcspkr && echo "blacklist pcspkr" > /mnt/etc/modprobe.d/nobeep.conf
-
-### ADDITIONAL CONFIGURATIONS ###
 
 # allow zsh startup files to be sourced from a different location at startup
 tee -a /mnt/etc/zsh/zshenv >/dev/null << EOF
@@ -441,6 +481,9 @@ arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootlo
 arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
 
 ### FINALIZE ###
+
+# copy this directory to root user's home
+cp -rf "$PWD" /mnt/root > /dev/null 2>&1
 
 # unmount the partitions
 umount -R /mnt
