work in progress

diff --git a/archinstall b/archinstall
--- a/archinstall
+++ b/archinstall
@@ -8,6 +8,10 @@ end() {
   printf '%s\n' "$1" >&2 && exit 1 # log to stderr and exit with failure
 }
 
+warn() {
+  gum style --foreground 161 "$1"
+}
+
 install() {
   pacman --noconfirm --needed -S "$1" >/dev/null 2>&1
 }
@@ -24,16 +28,26 @@ welcome() {
 This script installs a minimal Arch Linux system."
 }
 
+get_username() {
+  username=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Account name: " \
+    --placeholder "(enter a name for the user account)")
+  while ! echo "$username" | grep -q "^[a-z_][a-z0-9_-]*$"; do
+    username=$(gum input --prompt.foreground 99 --prompt.bold \
+      --prompt "Try again. Account name: " \
+      --placeholder "(only lowercase letters, - and _ are allowed)")
+  done
+}
+
 get_password() {
   password=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Password: " \
-    --password --placeholder "(enter a password for the root user)")
+    --password --placeholder "(enter a password for $username)")
   verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
     --password --placeholder "(retype the password)")
   while ! [ "$password" = "$verify" ]; do
     unset verify
     password=$(gum input --prompt.foreground 99 --prompt.bold \
       --prompt "Try again. Password: " --password \
-      --placeholder "(enter a password for the root user)")
+      --placeholder "(enter a password for $username)")
     verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
       --password --placeholder "(retype the password)")
   done
@@ -270,22 +284,20 @@ header "Installing packages"
 
 # install the essential packages
 gum spin --spinner line --title "Installing essential packages..." -- \
-  pacstrap -K /mnt linux linux-firmware linux-headers base ${vendor}-ucode \
-    grub efibootmgr doas dash zsh reflector networkmanager neovim terminus-font
+  pacstrap -K /mnt linux linux-firmware linux-headers base base-devel ${vendor}-ucode \
+    grub efibootmgr doas dash zsh gum reflector networkmanager neovim terminus-font
 
-# activate services
+# to allow connecting to the internet on reboot
 arch-chroot /mnt systemctl enable NetworkManager
 arch-chroot /mnt systemctl stop NetworkManager
-# arch-chroot /mnt systemctl enable bluetooth
-# arch-chroot /mnt systemctl enable cups.service
-# arch-chroot /mnt systemctl enable reflector.timer
 
-### CONFIGURE THE NEW SYSTEM ###
+### SYSTEM CONFIGURATION ###
 
 header "Generating filesystem table"
 
 # generate a filesystem table (fstab) file using UUID
 genfstab -U /mnt >> /mnt/etc/fstab
+
 # print fstab to stdout
 genfstab -U /mnt
 
@@ -321,14 +333,67 @@ arch-chroot /mnt tee -a /etc/hosts >/dev/null << EOT
 127.0.1.1    ${hostname}.localdomain $hostname
 EOT
 
-### CONFIGURATION ###
+### USER CONFIGURATION ###
+
+arch-chroot /mnt useradd -m -g wheel -s /usr/bin/zsh "$username" ||
+  warn "the user $username already exists"
+
+# set password for the new user
+echo "$username:$password" | arch-chroot /mnt chpasswd ||
+  warn "error setting the password for $username"
 
 # set password for the root user
-echo "root:$password" | arch-chroot /mnt chpasswd
-# unset password verify
+echo "root:$password" | arch-chroot /mnt chpasswd && unset password verify
+
+# permit wheel users to sudo with password
+echo "%wheel ALL=(ALL:ALL) ALL" > /mnt/etc/sudoers.d/00-wheel-can-sudo
+
+# allow some system commands to run without password
+echo "%wheel ALL=(ALL:ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/mount,\
+  /usr/bin/umount,/usr/bin/pacman -S,/usr/bin/pacman -Sy,/usr/bin/pacman -Syu" \
+  > /mnt/etc/sudoers.d/01-no-password-commands
+
+# set the default editor for visudo
+echo "Defaults editor=/usr/bin/nvim" > /mnt/etc/sudoers.d/02-visudo-editor
 
 # permit the wheel group to use doas with password
 echo "permit persist keepenv :wheel" > /mnt/etc/doas.conf
+
+# enable the multilib repository
+sed -i '/^#.multilib]$/s/^#//;/^.multilib]$/{n;s/^#//}' /mnt/etc/pacman.conf
+
+# configure pacman misc options
+sed -i '/^#Color/s/^#//;/^#ILoveCandy/s/^#//;/^#ParallelDownloads/s/^#//' /mnt/etc/pacman.conf
+
+# use all cores when compiling packages with makepkg
+sed -i "/^#MAKEFLAGS/s/^#//;s/-j2/-j$(nproc)/" /mnt/etc/makepkg.conf
+
+# beep begone!
+rmmod pcspkr && echo "blacklist pcspkr" > /mnt/etc/modprobe.d/nobeep.conf
+
+### ADDITIONAL CONFIGURATIONS ###
+
+# allow zsh startup files to be sourced from a different location at startup
+tee -a /mnt/etc/zsh/zshenv >/dev/null << EOF
+for z in zshenv zprofile zshrc; do
+  # source in the same order as indicated in zsh(1)
+  [ -f "\$HOME/.config/zsh/\$z" ] && source "\$HOME/.config/zsh/\$z"
+done && unset z
+EOF
+
+# set up the reflector service
+tee /mnt/etc/xdg/reflector/reflector.conf >/dev/null << EOF
+# reflector configuration file for the systemd service
+--protocol https
+--country US
+--latest 45
+--fastest 15
+--save /etc/pacman.d/mirrorlist
+EOF
+
+# allow reflector to update the mirrorlist periodically (weekly by default)
+arch-chroot /mnt systemctl enable reflector.timer
+arch-chroot /mnt systemctl stop reflector.timer
 
 ### BOOT LOADER ###
 
@@ -342,13 +407,13 @@ arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
 
 ### FINALIZE ###
 
-# copy this directory to the root directory to have access to it after rebooting
-cp -rf "$PWD" /mnt/root/
-
 # unmount the partitions
 umount /mnt/boot && umount /mnt
 
 # installation complete
 gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
   "Installation complete. If there were no error messages, please reboot and login \
-as the root user."
+as $username."
+
+# done
+finalize
